package info.jchein.mesosphere.elevator.domain.car.event

enum CarEventType {
	DROP_OFF_REQUESTED,
	DESTINATION_REQUIRED,
	SLOWED_NEAR_FLOOR,
	TRAVELLED_THROUGH_FLOOR,
	DEPARTED_PREVIOUS_FLOOR,
	PARKED_FOR_BOARDING;
}
