package info.jchein.mesosphere.elevator.domain.car.event

enum CarEventType {
	DESTINATION_CHANGED,
	DESTINATION_RETAINED,
	DROP_OFF_REQUESTED,
	CLEARED_FOR_DEPARTURE,
	DOOR_COUNTER_UPDATED,
	SLOWED_NEAR_FLOOR,
	TRAVELLED_THROUGH_FLOOR,
	DEPARTED_FROM_FLOOR,
	PARKED_FOR_BOARDING;
}
