package info.jchein.mesosphere.elevator.simulator.event;

public enum SimulationEventType
{
//   SIMULATION_CREATED,
   POPULATION_DEFINED,
//   SIMULATION_EPOCH_ADVANCED,
   TRAVELLER_ARRIVED,
   PICKUP_REQUESTED,
   BOARDED_ELEVATOR,
   DISEMBARKED_ELEVATOR, 
   TRAVELLER_DEPARTED
//   SIMULATION_ENDED
   ;
}
